apiVersion: v1
kind: Service
metadata:
  name: service-app
spec:
  selector:
    app: hello-app
  ports:
    - port: 3000
      nodePort: 31320
      protocol: TCP
      targetPort: 3000
  type: NodePort