- name: Create .kube directory for vagrant user
  file:
    path: /home/vagrant/.kube
    state: directory
- name: Upload kubeconfig to the node
  copy:
    src: ~/.kube/config
    dest: /home/vagrant/.kube/config
- name: Install flannel pod network
  become: false
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml    
- name: Apply k8s manifest files to launch the application
  script: launch.sh
  become: false