- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
     - mkdir -p /home/vagrant/.kube
     - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
     - chown vagrant:vagrant /home/vagrant/.kube/config
- name: Copy kubeconfig to local
  fetch:
      src: /home/vagrant/.kube/config
      dest: ~/.kube/config
      flat: yes